package com.hd.domain;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table apply_record
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class ApplyRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_record.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   申请状态 0-等待设计师操作 1-设计师接受 2-设计师拒绝
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_record.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * Database Column Remarks:
     *   操作时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_record.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * Database Column Remarks:
     *   申请用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_record. user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   设计师id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_record.designer_id
     *
     * @mbggenerated
     */
    private String designerId;

    /**
     * Database Column Remarks:
     *   装修申请id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_record.apply_id
     *
     * @mbggenerated
     */
    private String applyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table apply_record
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;
    
    /** 手动添加的属性 */
    private List<String> applyIds;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_record
     *
     * @mbggenerated
     */
    public ApplyRecord(String id, String status, Date time, String userId, String designerId, String applyId) {
        this.id = id;
        this.status = status;
        this.time = time;
        this.userId = userId;
        this.designerId = designerId;
        this.applyId = applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_record
     *
     * @mbggenerated
     */
    public ApplyRecord() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_record.id
     *
     * @return the value of apply_record.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_record.id
     *
     * @param id the value for apply_record.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_record.status
     *
     * @return the value of apply_record.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_record.status
     *
     * @param status the value for apply_record.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_record.time
     *
     * @return the value of apply_record.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_record.time
     *
     * @param time the value for apply_record.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_record. user_id
     *
     * @return the value of apply_record. user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_record. user_id
     *
     * @param userId the value for apply_record. user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_record.designer_id
     *
     * @return the value of apply_record.designer_id
     *
     * @mbggenerated
     */
    public String getDesignerId() {
        return designerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_record.designer_id
     *
     * @param designerId the value for apply_record.designer_id
     *
     * @mbggenerated
     */
    public void setDesignerId(String designerId) {
        this.designerId = designerId == null ? null : designerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_record.apply_id
     *
     * @return the value of apply_record.apply_id
     *
     * @mbggenerated
     */
    public String getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_record.apply_id
     *
     * @param applyId the value for apply_record.apply_id
     *
     * @mbggenerated
     */
    public void setApplyId(String applyId) {
        this.applyId = applyId == null ? null : applyId.trim();
    }

	public List<String> getApplyIds() {
		return applyIds;
	}

	public void setApplyIds(List<String> applyIds) {
		this.applyIds = applyIds;
	}
    
}