package com.hd.domain;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table apply_attachment
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class ApplyAttachment implements Serializable {
    

    /** 自己添加的属性  */
    
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column apply_attachment.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * Database Column Remarks: 附件名称 This field was generated by MyBatis Generator. This field corresponds to the database column apply_attachment.attachment_name
	 * @mbggenerated
	 */
	private String attachmentName;
	/**
	 * Database Column Remarks: 装修申请id This field was generated by MyBatis Generator. This field corresponds to the database column apply_attachment.apply_id
	 * @mbggenerated
	 */
	private String applyId;
	/**
	 * Database Column Remarks: 资源id(img_source表id) This field was generated by MyBatis Generator. This field corresponds to the database column apply_attachment.source_id
	 * @mbggenerated
	 */
	private String sourceId;
	/**
	 * Database Column Remarks: 附件类型 '0'-申请附件 '1'-设计成品 '2'-效果图 This field was generated by MyBatis Generator. This field corresponds to the database column apply_attachment.type
	 * @mbggenerated
	 */
	private String type;
	/**
	 * Database Column Remarks: 附件状态 '0'-正常  '1'-删除 This field was generated by MyBatis Generator. This field corresponds to the database column apply_attachment.status
	 * @mbggenerated
	 */
	private String status;
	/**
	 * Database Column Remarks: 创建时间 This field was generated by MyBatis Generator. This field corresponds to the database column apply_attachment.create_time
	 * @mbggenerated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table apply_attachment
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply_attachment
	 * @mbggenerated
	 */
	public ApplyAttachment(String id, String attachmentName, String applyId,
			String sourceId, String type, String status, Date createTime) {
		this.id = id;
		this.attachmentName = attachmentName;
		this.applyId = applyId;
		this.sourceId = sourceId;
		this.type = type;
		this.status = status;
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply_attachment
	 * @mbggenerated
	 */
	public ApplyAttachment() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column apply_attachment.id
	 * @return  the value of apply_attachment.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column apply_attachment.id
	 * @param id  the value for apply_attachment.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column apply_attachment.attachment_name
	 * @return  the value of apply_attachment.attachment_name
	 * @mbggenerated
	 */
	public String getAttachmentName() {
		return attachmentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column apply_attachment.attachment_name
	 * @param attachmentName  the value for apply_attachment.attachment_name
	 * @mbggenerated
	 */
	public void setAttachmentName(String attachmentName) {
		this.attachmentName = attachmentName == null ? null : attachmentName
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column apply_attachment.apply_id
	 * @return  the value of apply_attachment.apply_id
	 * @mbggenerated
	 */
	public String getApplyId() {
		return applyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column apply_attachment.apply_id
	 * @param applyId  the value for apply_attachment.apply_id
	 * @mbggenerated
	 */
	public void setApplyId(String applyId) {
		this.applyId = applyId == null ? null : applyId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column apply_attachment.source_id
	 * @return  the value of apply_attachment.source_id
	 * @mbggenerated
	 */
	public String getSourceId() {
		return sourceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column apply_attachment.source_id
	 * @param sourceId  the value for apply_attachment.source_id
	 * @mbggenerated
	 */
	public void setSourceId(String sourceId) {
		this.sourceId = sourceId == null ? null : sourceId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column apply_attachment.type
	 * @return  the value of apply_attachment.type
	 * @mbggenerated
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column apply_attachment.type
	 * @param type  the value for apply_attachment.type
	 * @mbggenerated
	 */
	public void setType(String type) {
		this.type = type == null ? null : type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column apply_attachment.status
	 * @return  the value of apply_attachment.status
	 * @mbggenerated
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column apply_attachment.status
	 * @param status  the value for apply_attachment.status
	 * @mbggenerated
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column apply_attachment.create_time
	 * @return  the value of apply_attachment.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column apply_attachment.create_time
	 * @param createTime  the value for apply_attachment.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
     * 资源路径
     */
    private String sourcePath;
    
    public String getSourcePath() {
		return sourcePath;
	}

	public void setSourcePath(String sourcePath) {
		this.sourcePath = sourcePath;
	}
    
}