package com.hd.domain;

import java.io.Serializable;
import java.util.Date;

public class DecorationApply implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoration_apply.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoration_apply.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoration_apply.budget_amount
     *
     * @mbg.generated
     */
    private String budgetAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoration_apply.area
     *
     * @mbg.generated
     */
    private Long area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoration_apply.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoration_apply.comment_rating
     *
     * @mbg.generated
     */
    private String commentRating;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoration_apply.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoration_apply.pass_time
     *
     * @mbg.generated
     */
    private Date passTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoration_apply.accept_id
     *
     * @mbg.generated
     */
    private String acceptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoration_apply.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table decoration_apply
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_apply
     *
     * @mbg.generated
     */
    public DecorationApply(String id, String type, String budgetAmount, Long area, String status, String commentRating, Date createTime, Date passTime, String acceptId, String userId) {
        this.id = id;
        this.type = type;
        this.budgetAmount = budgetAmount;
        this.area = area;
        this.status = status;
        this.commentRating = commentRating;
        this.createTime = createTime;
        this.passTime = passTime;
        this.acceptId = acceptId;
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_apply
     *
     * @mbg.generated
     */
    public DecorationApply() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoration_apply.id
     *
     * @return the value of decoration_apply.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoration_apply.id
     *
     * @param id the value for decoration_apply.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoration_apply.type
     *
     * @return the value of decoration_apply.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoration_apply.type
     *
     * @param type the value for decoration_apply.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoration_apply.budget_amount
     *
     * @return the value of decoration_apply.budget_amount
     *
     * @mbg.generated
     */
    public String getBudgetAmount() {
        return budgetAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoration_apply.budget_amount
     *
     * @param budgetAmount the value for decoration_apply.budget_amount
     *
     * @mbg.generated
     */
    public void setBudgetAmount(String budgetAmount) {
        this.budgetAmount = budgetAmount == null ? null : budgetAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoration_apply.area
     *
     * @return the value of decoration_apply.area
     *
     * @mbg.generated
     */
    public Long getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoration_apply.area
     *
     * @param area the value for decoration_apply.area
     *
     * @mbg.generated
     */
    public void setArea(Long area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoration_apply.status
     *
     * @return the value of decoration_apply.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoration_apply.status
     *
     * @param status the value for decoration_apply.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoration_apply.comment_rating
     *
     * @return the value of decoration_apply.comment_rating
     *
     * @mbg.generated
     */
    public String getCommentRating() {
        return commentRating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoration_apply.comment_rating
     *
     * @param commentRating the value for decoration_apply.comment_rating
     *
     * @mbg.generated
     */
    public void setCommentRating(String commentRating) {
        this.commentRating = commentRating == null ? null : commentRating.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoration_apply.create_time
     *
     * @return the value of decoration_apply.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoration_apply.create_time
     *
     * @param createTime the value for decoration_apply.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoration_apply.pass_time
     *
     * @return the value of decoration_apply.pass_time
     *
     * @mbg.generated
     */
    public Date getPassTime() {
        return passTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoration_apply.pass_time
     *
     * @param passTime the value for decoration_apply.pass_time
     *
     * @mbg.generated
     */
    public void setPassTime(Date passTime) {
        this.passTime = passTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoration_apply.accept_id
     *
     * @return the value of decoration_apply.accept_id
     *
     * @mbg.generated
     */
    public String getAcceptId() {
        return acceptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoration_apply.accept_id
     *
     * @param acceptId the value for decoration_apply.accept_id
     *
     * @mbg.generated
     */
    public void setAcceptId(String acceptId) {
        this.acceptId = acceptId == null ? null : acceptId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoration_apply.user_id
     *
     * @return the value of decoration_apply.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoration_apply.user_id
     *
     * @param userId the value for decoration_apply.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_apply
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DecorationApply other = (DecorationApply) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getBudgetAmount() == null ? other.getBudgetAmount() == null : this.getBudgetAmount().equals(other.getBudgetAmount()))
            && (this.getArea() == null ? other.getArea() == null : this.getArea().equals(other.getArea()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCommentRating() == null ? other.getCommentRating() == null : this.getCommentRating().equals(other.getCommentRating()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getPassTime() == null ? other.getPassTime() == null : this.getPassTime().equals(other.getPassTime()))
            && (this.getAcceptId() == null ? other.getAcceptId() == null : this.getAcceptId().equals(other.getAcceptId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_apply
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getBudgetAmount() == null) ? 0 : getBudgetAmount().hashCode());
        result = prime * result + ((getArea() == null) ? 0 : getArea().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCommentRating() == null) ? 0 : getCommentRating().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getPassTime() == null) ? 0 : getPassTime().hashCode());
        result = prime * result + ((getAcceptId() == null) ? 0 : getAcceptId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        return result;
    }
}