package com.hd.domain;

import java.io.Serializable;

public class DecorationStyle implements Serializable {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column decoration_style.id
	 * @mbggenerated
	 */
	private String id;

	/**
	 * Database Column Remarks: 风格名称 This field was generated by MyBatis Generator. This field corresponds to the database column decoration_style.name
	 * @mbggenerated
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table decoration_style
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_style
	 * @mbggenerated
	 */
	public DecorationStyle(String id, String name) {
		this.id = id;
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_style
	 * @mbggenerated
	 */
	public DecorationStyle() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column decoration_style.id
	 * @return  the value of decoration_style.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column decoration_style.id
	 * @param id  the value for decoration_style.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column decoration_style.name
	 * @return  the value of decoration_style.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column decoration_style.name
	 * @param name  the value for decoration_style.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

}