package com.hd.domain;

import java.io.Serializable;
import java.util.Date;

public class DecorationEffect implements Serializable {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column decoration_effect.id
	 * @mbggenerated
	 */
	private String id;

	/**
	 * Database Column Remarks: 设计师id This field was generated by MyBatis Generator. This field corresponds to the database column decoration_effect.designer_id
	 * @mbggenerated
	 */
	private String designerId;

	/**
	 * Database Column Remarks: 装修申请id This field was generated by MyBatis Generator. This field corresponds to the database column decoration_effect.apply_id
	 * @mbggenerated
	 */
	private String applyId;

	/**
	 * Database Column Remarks: 展示名称 This field was generated by MyBatis Generator. This field corresponds to the database column decoration_effect.title
	 * @mbggenerated
	 */
	private String title;

	/**
	 * Database Column Remarks: 创建时间 This field was generated by MyBatis Generator. This field corresponds to the database column decoration_effect.create_time
	 * @mbggenerated
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table decoration_effect
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_effect
	 * @mbggenerated
	 */
	public DecorationEffect(String id, String designerId, String applyId,
			String title, Date createTime) {
		this.id = id;
		this.designerId = designerId;
		this.applyId = applyId;
		this.title = title;
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_effect
	 * @mbggenerated
	 */
	public DecorationEffect() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column decoration_effect.id
	 * @return  the value of decoration_effect.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column decoration_effect.id
	 * @param id  the value for decoration_effect.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column decoration_effect.designer_id
	 * @return  the value of decoration_effect.designer_id
	 * @mbggenerated
	 */
	public String getDesignerId() {
		return designerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column decoration_effect.designer_id
	 * @param designerId  the value for decoration_effect.designer_id
	 * @mbggenerated
	 */
	public void setDesignerId(String designerId) {
		this.designerId = designerId == null ? null : designerId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column decoration_effect.apply_id
	 * @return  the value of decoration_effect.apply_id
	 * @mbggenerated
	 */
	public String getApplyId() {
		return applyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column decoration_effect.apply_id
	 * @param applyId  the value for decoration_effect.apply_id
	 * @mbggenerated
	 */
	public void setApplyId(String applyId) {
		this.applyId = applyId == null ? null : applyId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column decoration_effect.title
	 * @return  the value of decoration_effect.title
	 * @mbggenerated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column decoration_effect.title
	 * @param title  the value for decoration_effect.title
	 * @mbggenerated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column decoration_effect.create_time
	 * @return  the value of decoration_effect.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column decoration_effect.create_time
	 * @param createTime  the value for decoration_effect.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}