package com.hd.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class DecorationApply implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column decoration_apply.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * Database Column Remarks: 装修类型 0-面议 1-半包 2-全包 This field was generated by MyBatis Generator. This field corresponds to the database column decoration_apply.type
	 * @mbggenerated
	 */
	private String type;
	/**
	 * Database Column Remarks: 预算金额(-1则表示面议 0-三万以下 1- 3~5万 2- 5~8万 3- 8~10万 4- 10~12万 5- 12~15万 6- 15~30万 7- 30万以上） This field was generated by MyBatis Generator. This field corresponds to the database column decoration_apply.budget_amount
	 * @mbggenerated
	 */
	private String budgetAmount;
	/**
	 * Database Column Remarks: 装修面积 This field was generated by MyBatis Generator. This field corresponds to the database column decoration_apply.area
	 * @mbggenerated
	 */
	private BigDecimal area;
	/**
	 * Database Column Remarks: 状态 0-申请中 1-申请通过(发布) 2-申请失败 3-已接受 4-拒绝接受已设计的方案 5-正在装修 6装修完成 This field was generated by MyBatis Generator. This field corresponds to the database column decoration_apply.status
	 * @mbggenerated
	 */
	private String status;
	/**
	 * Database Column Remarks: 评论等级 0-差评 1-一般 2-好评 This field was generated by MyBatis Generator. This field corresponds to the database column decoration_apply.comment_rating
	 * @mbggenerated
	 */
	private String commentRating;
	/**
	 * Database Column Remarks: 预约申请时间 This field was generated by MyBatis Generator. This field corresponds to the database column decoration_apply.create_time
	 * @mbggenerated
	 */
	private Date createTime;
	/**
	 * Database Column Remarks: 申请审核时间(通过则为发布时间) This field was generated by MyBatis Generator. This field corresponds to the database column decoration_apply.check_time
	 * @mbggenerated
	 */
	private Date checkTime;
	/**
	 * Database Column Remarks: 拒绝接受设计时间 This field was generated by MyBatis Generator. This field corresponds to the database column decoration_apply.refuse_time
	 * @mbggenerated
	 */
	private Date refuseTime;
	/**
	 * Database Column Remarks: 设计师id This field was generated by MyBatis Generator. This field corresponds to the database column decoration_apply.accept_id
	 * @mbggenerated
	 */
	private String acceptId;
	/**
	 * Database Column Remarks: 设计师接受时间 This field was generated by MyBatis Generator. This field corresponds to the database column decoration_apply.accept_time
	 * @mbggenerated
	 */
	private Date acceptTime;
	/**
	 * Database Column Remarks: 用户id  This field was generated by MyBatis Generator. This field corresponds to the database column decoration_apply.user_id
	 * @mbggenerated
	 */
	private String userId;
	/**
	 * Database Column Remarks: 装修完成时间 This field was generated by MyBatis Generator. This field corresponds to the database column decoration_apply.finish_time
	 * @mbggenerated
	 */
	private Date finishTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table decoration_apply
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_apply
	 * @mbggenerated
	 */
	public DecorationApply(String id, String type, String budgetAmount,
			BigDecimal area, String status, String commentRating,
			Date createTime, Date checkTime, Date refuseTime, String acceptId,
			Date acceptTime, String userId, Date finishTime) {
		this.id = id;
		this.type = type;
		this.budgetAmount = budgetAmount;
		this.area = area;
		this.status = status;
		this.commentRating = commentRating;
		this.createTime = createTime;
		this.checkTime = checkTime;
		this.refuseTime = refuseTime;
		this.acceptId = acceptId;
		this.acceptTime = acceptTime;
		this.userId = userId;
		this.finishTime = finishTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_apply
	 * @mbggenerated
	 */
	public DecorationApply() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column decoration_apply.id
	 * @return  the value of decoration_apply.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column decoration_apply.id
	 * @param id  the value for decoration_apply.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column decoration_apply.type
	 * @return  the value of decoration_apply.type
	 * @mbggenerated
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column decoration_apply.type
	 * @param type  the value for decoration_apply.type
	 * @mbggenerated
	 */
	public void setType(String type) {
		this.type = type == null ? null : type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column decoration_apply.budget_amount
	 * @return  the value of decoration_apply.budget_amount
	 * @mbggenerated
	 */
	public String getBudgetAmount() {
		return budgetAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column decoration_apply.budget_amount
	 * @param budgetAmount  the value for decoration_apply.budget_amount
	 * @mbggenerated
	 */
	public void setBudgetAmount(String budgetAmount) {
		this.budgetAmount = budgetAmount == null ? null : budgetAmount.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column decoration_apply.area
	 * @return  the value of decoration_apply.area
	 * @mbggenerated
	 */
	public BigDecimal getArea() {
		return area;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column decoration_apply.area
	 * @param area  the value for decoration_apply.area
	 * @mbggenerated
	 */
	public void setArea(BigDecimal area) {
		this.area = area;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column decoration_apply.status
	 * @return  the value of decoration_apply.status
	 * @mbggenerated
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column decoration_apply.status
	 * @param status  the value for decoration_apply.status
	 * @mbggenerated
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column decoration_apply.comment_rating
	 * @return  the value of decoration_apply.comment_rating
	 * @mbggenerated
	 */
	public String getCommentRating() {
		return commentRating;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column decoration_apply.comment_rating
	 * @param commentRating  the value for decoration_apply.comment_rating
	 * @mbggenerated
	 */
	public void setCommentRating(String commentRating) {
		this.commentRating = commentRating == null ? null : commentRating
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column decoration_apply.create_time
	 * @return  the value of decoration_apply.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column decoration_apply.create_time
	 * @param createTime  the value for decoration_apply.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column decoration_apply.check_time
	 * @return  the value of decoration_apply.check_time
	 * @mbggenerated
	 */
	public Date getCheckTime() {
		return checkTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column decoration_apply.check_time
	 * @param checkTime  the value for decoration_apply.check_time
	 * @mbggenerated
	 */
	public void setCheckTime(Date checkTime) {
		this.checkTime = checkTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column decoration_apply.refuse_time
	 * @return  the value of decoration_apply.refuse_time
	 * @mbggenerated
	 */
	public Date getRefuseTime() {
		return refuseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column decoration_apply.refuse_time
	 * @param refuseTime  the value for decoration_apply.refuse_time
	 * @mbggenerated
	 */
	public void setRefuseTime(Date refuseTime) {
		this.refuseTime = refuseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column decoration_apply.accept_id
	 * @return  the value of decoration_apply.accept_id
	 * @mbggenerated
	 */
	public String getAcceptId() {
		return acceptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column decoration_apply.accept_id
	 * @param acceptId  the value for decoration_apply.accept_id
	 * @mbggenerated
	 */
	public void setAcceptId(String acceptId) {
		this.acceptId = acceptId == null ? null : acceptId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column decoration_apply.accept_time
	 * @return  the value of decoration_apply.accept_time
	 * @mbggenerated
	 */
	public Date getAcceptTime() {
		return acceptTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column decoration_apply.accept_time
	 * @param acceptTime  the value for decoration_apply.accept_time
	 * @mbggenerated
	 */
	public void setAcceptTime(Date acceptTime) {
		this.acceptTime = acceptTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column decoration_apply.user_id
	 * @return  the value of decoration_apply.user_id
	 * @mbggenerated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column decoration_apply.user_id
	 * @param userId  the value for decoration_apply.user_id
	 * @mbggenerated
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column decoration_apply.finish_time
	 * @return  the value of decoration_apply.finish_time
	 * @mbggenerated
	 */
	public Date getFinishTime() {
		return finishTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column decoration_apply.finish_time
	 * @param finishTime  the value for decoration_apply.finish_time
	 * @mbggenerated
	 */
	public void setFinishTime(Date finishTime) {
		this.finishTime = finishTime;
	}
}