package com.hd.domain;

import java.io.Serializable;

public class DecorationEffectImg implements Serializable {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column decoration_effect_img.id
	 * @mbggenerated
	 */
	private String id;

	/**
	 * Database Column Remarks: 装修效果表id This field was generated by MyBatis Generator. This field corresponds to the database column decoration_effect_img.effect_id
	 * @mbggenerated
	 */
	private String effectId;

	/**
	 * Database Column Remarks: 装修申请id This field was generated by MyBatis Generator. This field corresponds to the database column decoration_effect_img.apply_id
	 * @mbggenerated
	 */
	private String applyId;

	/**
	 * Database Column Remarks: 图片地址 This field was generated by MyBatis Generator. This field corresponds to the database column decoration_effect_img.img
	 * @mbggenerated
	 */
	private String img;

	/**
	 * Database Column Remarks: 效果图名称 This field was generated by MyBatis Generator. This field corresponds to the database column decoration_effect_img.title
	 * @mbggenerated
	 */
	private String title;
	
	private String imgPath;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table decoration_effect_img
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_effect_img
	 * @mbggenerated
	 */
	public DecorationEffectImg(String id, String effectId, String applyId,
			String img, String title) {
		this.id = id;
		this.effectId = effectId;
		this.applyId = applyId;
		this.img = img;
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_effect_img
	 * @mbggenerated
	 */
	public DecorationEffectImg() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column decoration_effect_img.id
	 * @return  the value of decoration_effect_img.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column decoration_effect_img.id
	 * @param id  the value for decoration_effect_img.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column decoration_effect_img.effect_id
	 * @return  the value of decoration_effect_img.effect_id
	 * @mbggenerated
	 */
	public String getEffectId() {
		return effectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column decoration_effect_img.effect_id
	 * @param effectId  the value for decoration_effect_img.effect_id
	 * @mbggenerated
	 */
	public void setEffectId(String effectId) {
		this.effectId = effectId == null ? null : effectId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column decoration_effect_img.apply_id
	 * @return  the value of decoration_effect_img.apply_id
	 * @mbggenerated
	 */
	public String getApplyId() {
		return applyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column decoration_effect_img.apply_id
	 * @param applyId  the value for decoration_effect_img.apply_id
	 * @mbggenerated
	 */
	public void setApplyId(String applyId) {
		this.applyId = applyId == null ? null : applyId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column decoration_effect_img.img
	 * @return  the value of decoration_effect_img.img
	 * @mbggenerated
	 */
	public String getImg() {
		return img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column decoration_effect_img.img
	 * @param img  the value for decoration_effect_img.img
	 * @mbggenerated
	 */
	public void setImg(String img) {
		this.img = img == null ? null : img.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column decoration_effect_img.title
	 * @return  the value of decoration_effect_img.title
	 * @mbggenerated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column decoration_effect_img.title
	 * @param title  the value for decoration_effect_img.title
	 * @mbggenerated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	public String getImgPath() {
		return imgPath;
	}

	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}
}