package com.hd.domain;

import java.io.Serializable;

public class DecorationEffectKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column decoration_effect_key.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * Database Column Remarks: 装修效果id This field was generated by MyBatis Generator. This field corresponds to the database column decoration_effect_key.effect_id
	 * @mbggenerated
	 */
	private String effectId;
	/**
	 * Database Column Remarks: 关键字 This field was generated by MyBatis Generator. This field corresponds to the database column decoration_effect_key.key_word
	 * @mbggenerated
	 */
	private String keyWord;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table decoration_effect_key
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;
	
	/**手动添加的属性 */
	private String keyWordName;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_effect_key
	 * @mbggenerated
	 */
	public DecorationEffectKey(String id, String effectId, String keyWord) {
		this.id = id;
		this.effectId = effectId;
		this.keyWord = keyWord;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_effect_key
	 * @mbggenerated
	 */
	public DecorationEffectKey() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column decoration_effect_key.id
	 * @return  the value of decoration_effect_key.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column decoration_effect_key.id
	 * @param id  the value for decoration_effect_key.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column decoration_effect_key.effect_id
	 * @return  the value of decoration_effect_key.effect_id
	 * @mbggenerated
	 */
	public String getEffectId() {
		return effectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column decoration_effect_key.effect_id
	 * @param effectId  the value for decoration_effect_key.effect_id
	 * @mbggenerated
	 */
	public void setEffectId(String effectId) {
		this.effectId = effectId == null ? null : effectId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column decoration_effect_key.key_word
	 * @return  the value of decoration_effect_key.key_word
	 * @mbggenerated
	 */
	public String getKeyWord() {
		return keyWord;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column decoration_effect_key.key_word
	 * @param keyWord  the value for decoration_effect_key.key_word
	 * @mbggenerated
	 */
	public void setKeyWord(String keyWord) {
		this.keyWord = keyWord == null ? null : keyWord.trim();
	}

	public String getKeyWordName() {
		return keyWordName;
	}

	public void setKeyWordName(String keyWordName) {
		this.keyWordName = keyWordName;
	}
}