package com.hd.domain;

import java.io.Serializable;

public class DecorationEffectKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoration_effect_key.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoration_effect_key.effect_id
     *
     * @mbg.generated
     */
    private String effectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoration_effect_key.key
     *
     * @mbg.generated
     */
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table decoration_effect_key
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_effect_key
     *
     * @mbg.generated
     */
    public DecorationEffectKey(String id, String effectId, String key) {
        this.id = id;
        this.effectId = effectId;
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_effect_key
     *
     * @mbg.generated
     */
    public DecorationEffectKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoration_effect_key.id
     *
     * @return the value of decoration_effect_key.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoration_effect_key.id
     *
     * @param id the value for decoration_effect_key.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoration_effect_key.effect_id
     *
     * @return the value of decoration_effect_key.effect_id
     *
     * @mbg.generated
     */
    public String getEffectId() {
        return effectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoration_effect_key.effect_id
     *
     * @param effectId the value for decoration_effect_key.effect_id
     *
     * @mbg.generated
     */
    public void setEffectId(String effectId) {
        this.effectId = effectId == null ? null : effectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoration_effect_key.key
     *
     * @return the value of decoration_effect_key.key
     *
     * @mbg.generated
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoration_effect_key.key
     *
     * @param key the value for decoration_effect_key.key
     *
     * @mbg.generated
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_effect_key
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DecorationEffectKey other = (DecorationEffectKey) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getEffectId() == null ? other.getEffectId() == null : this.getEffectId().equals(other.getEffectId()))
            && (this.getKey() == null ? other.getKey() == null : this.getKey().equals(other.getKey()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_effect_key
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getEffectId() == null) ? 0 : getEffectId().hashCode());
        result = prime * result + ((getKey() == null) ? 0 : getKey().hashCode());
        return result;
    }
}