package com.hd.domain;

import java.io.Serializable;

public class DesignerStyle implements Serializable {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column designer_style.id
	 * @mbggenerated
	 */
	private String id;

	/**
	 * Database Column Remarks: 设计师id This field was generated by MyBatis Generator. This field corresponds to the database column designer_style.designer_id
	 * @mbggenerated
	 */
	private String designerId;

	/**
	 * Database Column Remarks: 风格id This field was generated by MyBatis Generator. This field corresponds to the database column designer_style.style_id
	 * @mbggenerated
	 */
	private String styleId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table designer_style
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table designer_style
	 * @mbggenerated
	 */
	public DesignerStyle(String id, String designerId, String styleId) {
		this.id = id;
		this.designerId = designerId;
		this.styleId = styleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table designer_style
	 * @mbggenerated
	 */
	public DesignerStyle() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column designer_style.id
	 * @return  the value of designer_style.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column designer_style.id
	 * @param id  the value for designer_style.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column designer_style.designer_id
	 * @return  the value of designer_style.designer_id
	 * @mbggenerated
	 */
	public String getDesignerId() {
		return designerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column designer_style.designer_id
	 * @param designerId  the value for designer_style.designer_id
	 * @mbggenerated
	 */
	public void setDesignerId(String designerId) {
		this.designerId = designerId == null ? null : designerId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column designer_style.style_id
	 * @return  the value of designer_style.style_id
	 * @mbggenerated
	 */
	public String getStyleId() {
		return styleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column designer_style.style_id
	 * @param styleId  the value for designer_style.style_id
	 * @mbggenerated
	 */
	public void setStyleId(String styleId) {
		this.styleId = styleId == null ? null : styleId.trim();
	}
	
}