package com.hd.domain;

import java.io.Serializable;
import java.math.BigDecimal;

public class DesignerWithBLOBs extends Designer implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column designer.introduce
	 * @mbggenerated
	 */
	private String introduce;
	/**
	 * Database Column Remarks: 其他记录(比如获奖) This field was generated by MyBatis Generator. This field corresponds to the database column designer.record
	 * @mbggenerated
	 */
	private String record;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table designer
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table designer
	 * @mbggenerated
	 */
	public DesignerWithBLOBs(String id, String userId, String serviceAddress,
			BigDecimal designAmountLow, BigDecimal designAmountHigh,
			Float engageTime, String positionalTitle, String status,
			String introduce, String record) {
		super(id, userId, serviceAddress, designAmountLow, designAmountHigh,
				engageTime, positionalTitle, status);
		this.introduce = introduce;
		this.record = record;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table designer
	 * @mbggenerated
	 */
	public DesignerWithBLOBs() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column designer.introduce
	 * @return  the value of designer.introduce
	 * @mbggenerated
	 */
	public String getIntroduce() {
		return introduce;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column designer.introduce
	 * @param introduce  the value for designer.introduce
	 * @mbggenerated
	 */
	public void setIntroduce(String introduce) {
		this.introduce = introduce == null ? null : introduce.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column designer.record
	 * @return  the value of designer.record
	 * @mbggenerated
	 */
	public String getRecord() {
		return record;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column designer.record
	 * @param record  the value for designer.record
	 * @mbggenerated
	 */
	public void setRecord(String record) {
		this.record = record == null ? null : record.trim();
	}

}