package com.hd.domain;

import java.io.Serializable;

public class Designer implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column designer.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column designer.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column designer.service_address
     *
     * @mbg.generated
     */
    private String serviceAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column designer.design_amount_low
     *
     * @mbg.generated
     */
    private Long designAmountLow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column designer.design_amount_high
     *
     * @mbg.generated
     */
    private Long designAmountHigh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column designer.engage_time
     *
     * @mbg.generated
     */
    private Float engageTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table designer
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table designer
     *
     * @mbg.generated
     */
    public Designer(String id, String userId, String serviceAddress, Long designAmountLow, Long designAmountHigh, Float engageTime) {
        this.id = id;
        this.userId = userId;
        this.serviceAddress = serviceAddress;
        this.designAmountLow = designAmountLow;
        this.designAmountHigh = designAmountHigh;
        this.engageTime = engageTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table designer
     *
     * @mbg.generated
     */
    public Designer() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column designer.id
     *
     * @return the value of designer.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column designer.id
     *
     * @param id the value for designer.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column designer.user_id
     *
     * @return the value of designer.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column designer.user_id
     *
     * @param userId the value for designer.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column designer.service_address
     *
     * @return the value of designer.service_address
     *
     * @mbg.generated
     */
    public String getServiceAddress() {
        return serviceAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column designer.service_address
     *
     * @param serviceAddress the value for designer.service_address
     *
     * @mbg.generated
     */
    public void setServiceAddress(String serviceAddress) {
        this.serviceAddress = serviceAddress == null ? null : serviceAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column designer.design_amount_low
     *
     * @return the value of designer.design_amount_low
     *
     * @mbg.generated
     */
    public Long getDesignAmountLow() {
        return designAmountLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column designer.design_amount_low
     *
     * @param designAmountLow the value for designer.design_amount_low
     *
     * @mbg.generated
     */
    public void setDesignAmountLow(Long designAmountLow) {
        this.designAmountLow = designAmountLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column designer.design_amount_high
     *
     * @return the value of designer.design_amount_high
     *
     * @mbg.generated
     */
    public Long getDesignAmountHigh() {
        return designAmountHigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column designer.design_amount_high
     *
     * @param designAmountHigh the value for designer.design_amount_high
     *
     * @mbg.generated
     */
    public void setDesignAmountHigh(Long designAmountHigh) {
        this.designAmountHigh = designAmountHigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column designer.engage_time
     *
     * @return the value of designer.engage_time
     *
     * @mbg.generated
     */
    public Float getEngageTime() {
        return engageTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column designer.engage_time
     *
     * @param engageTime the value for designer.engage_time
     *
     * @mbg.generated
     */
    public void setEngageTime(Float engageTime) {
        this.engageTime = engageTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table designer
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Designer other = (Designer) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getServiceAddress() == null ? other.getServiceAddress() == null : this.getServiceAddress().equals(other.getServiceAddress()))
            && (this.getDesignAmountLow() == null ? other.getDesignAmountLow() == null : this.getDesignAmountLow().equals(other.getDesignAmountLow()))
            && (this.getDesignAmountHigh() == null ? other.getDesignAmountHigh() == null : this.getDesignAmountHigh().equals(other.getDesignAmountHigh()))
            && (this.getEngageTime() == null ? other.getEngageTime() == null : this.getEngageTime().equals(other.getEngageTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table designer
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getServiceAddress() == null) ? 0 : getServiceAddress().hashCode());
        result = prime * result + ((getDesignAmountLow() == null) ? 0 : getDesignAmountLow().hashCode());
        result = prime * result + ((getDesignAmountHigh() == null) ? 0 : getDesignAmountHigh().hashCode());
        result = prime * result + ((getEngageTime() == null) ? 0 : getEngageTime().hashCode());
        return result;
    }
}