package com.hd.domain;

import java.io.Serializable;
import java.math.BigDecimal;

public class Designer implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column designer.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * Database Column Remarks: 用户id（user表id） This field was generated by MyBatis Generator. This field corresponds to the database column designer.user_id
	 * @mbggenerated
	 */
	private String userId;
	/**
	 * Database Column Remarks: 服务地址 This field was generated by MyBatis Generator. This field corresponds to the database column designer.service_address
	 * @mbggenerated
	 */
	private String serviceAddress;
	/**
	 * Database Column Remarks: 最低设计费用 This field was generated by MyBatis Generator. This field corresponds to the database column designer.design_amount_low
	 * @mbggenerated
	 */
	private BigDecimal designAmountLow;
	/**
	 * Database Column Remarks: 最高设计费用 This field was generated by MyBatis Generator. This field corresponds to the database column designer.design_amount_high
	 * @mbggenerated
	 */
	private BigDecimal designAmountHigh;
	/**
	 * Database Column Remarks: 从事设计时间 This field was generated by MyBatis Generator. This field corresponds to the database column designer.engage_time
	 * @mbggenerated
	 */
	private Float engageTime;
	/**
	 * Database Column Remarks: 设计师职称 This field was generated by MyBatis Generator. This field corresponds to the database column designer.positional_title
	 * @mbggenerated
	 */
	private String positionalTitle;
	/**
	 * Database Column Remarks: 状态 0-待审核 1- 审核通过 2-审核失败 This field was generated by MyBatis Generator. This field corresponds to the database column designer.status
	 * @mbggenerated
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table designer
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table designer
	 * @mbggenerated
	 */
	public Designer(String id, String userId, String serviceAddress,
			BigDecimal designAmountLow, BigDecimal designAmountHigh,
			Float engageTime, String positionalTitle, String status) {
		this.id = id;
		this.userId = userId;
		this.serviceAddress = serviceAddress;
		this.designAmountLow = designAmountLow;
		this.designAmountHigh = designAmountHigh;
		this.engageTime = engageTime;
		this.positionalTitle = positionalTitle;
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table designer
	 * @mbggenerated
	 */
	public Designer() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column designer.id
	 * @return  the value of designer.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column designer.id
	 * @param id  the value for designer.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column designer.user_id
	 * @return  the value of designer.user_id
	 * @mbggenerated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column designer.user_id
	 * @param userId  the value for designer.user_id
	 * @mbggenerated
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column designer.service_address
	 * @return  the value of designer.service_address
	 * @mbggenerated
	 */
	public String getServiceAddress() {
		return serviceAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column designer.service_address
	 * @param serviceAddress  the value for designer.service_address
	 * @mbggenerated
	 */
	public void setServiceAddress(String serviceAddress) {
		this.serviceAddress = serviceAddress == null ? null : serviceAddress
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column designer.design_amount_low
	 * @return  the value of designer.design_amount_low
	 * @mbggenerated
	 */
	public BigDecimal getDesignAmountLow() {
		return designAmountLow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column designer.design_amount_low
	 * @param designAmountLow  the value for designer.design_amount_low
	 * @mbggenerated
	 */
	public void setDesignAmountLow(BigDecimal designAmountLow) {
		this.designAmountLow = designAmountLow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column designer.design_amount_high
	 * @return  the value of designer.design_amount_high
	 * @mbggenerated
	 */
	public BigDecimal getDesignAmountHigh() {
		return designAmountHigh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column designer.design_amount_high
	 * @param designAmountHigh  the value for designer.design_amount_high
	 * @mbggenerated
	 */
	public void setDesignAmountHigh(BigDecimal designAmountHigh) {
		this.designAmountHigh = designAmountHigh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column designer.engage_time
	 * @return  the value of designer.engage_time
	 * @mbggenerated
	 */
	public Float getEngageTime() {
		return engageTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column designer.engage_time
	 * @param engageTime  the value for designer.engage_time
	 * @mbggenerated
	 */
	public void setEngageTime(Float engageTime) {
		this.engageTime = engageTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column designer.positional_title
	 * @return  the value of designer.positional_title
	 * @mbggenerated
	 */
	public String getPositionalTitle() {
		return positionalTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column designer.positional_title
	 * @param positionalTitle  the value for designer.positional_title
	 * @mbggenerated
	 */
	public void setPositionalTitle(String positionalTitle) {
		this.positionalTitle = positionalTitle == null ? null : positionalTitle
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column designer.status
	 * @return  the value of designer.status
	 * @mbggenerated
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column designer.status
	 * @param status  the value for designer.status
	 * @mbggenerated
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

}