package com.hd.domain;

import java.io.Serializable;

public class DesignerStyle implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column designer_style.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column designer_style.designer_id
     *
     * @mbg.generated
     */
    private String designerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column designer_style.style_id
     *
     * @mbg.generated
     */
    private String styleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table designer_style
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table designer_style
     *
     * @mbg.generated
     */
    public DesignerStyle(String id, String designerId, String styleId) {
        this.id = id;
        this.designerId = designerId;
        this.styleId = styleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table designer_style
     *
     * @mbg.generated
     */
    public DesignerStyle() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column designer_style.id
     *
     * @return the value of designer_style.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column designer_style.id
     *
     * @param id the value for designer_style.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column designer_style.designer_id
     *
     * @return the value of designer_style.designer_id
     *
     * @mbg.generated
     */
    public String getDesignerId() {
        return designerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column designer_style.designer_id
     *
     * @param designerId the value for designer_style.designer_id
     *
     * @mbg.generated
     */
    public void setDesignerId(String designerId) {
        this.designerId = designerId == null ? null : designerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column designer_style.style_id
     *
     * @return the value of designer_style.style_id
     *
     * @mbg.generated
     */
    public String getStyleId() {
        return styleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column designer_style.style_id
     *
     * @param styleId the value for designer_style.style_id
     *
     * @mbg.generated
     */
    public void setStyleId(String styleId) {
        this.styleId = styleId == null ? null : styleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table designer_style
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DesignerStyle other = (DesignerStyle) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getDesignerId() == null ? other.getDesignerId() == null : this.getDesignerId().equals(other.getDesignerId()))
            && (this.getStyleId() == null ? other.getStyleId() == null : this.getStyleId().equals(other.getStyleId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table designer_style
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getDesignerId() == null) ? 0 : getDesignerId().hashCode());
        result = prime * result + ((getStyleId() == null) ? 0 : getStyleId().hashCode());
        return result;
    }
}