package com.hd.domain;

import java.io.Serializable;
import java.util.Date;

public class ImgSource implements Serializable {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column img_source.id
	 * @mbggenerated
	 */
	private String id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column img_source.path
	 * @mbggenerated
	 */
	private String path;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column img_source.create_time
	 * @mbggenerated
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table img_source
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table img_source
	 * @mbggenerated
	 */
	public ImgSource(String id, String path, Date createTime) {
		this.id = id;
		this.path = path;
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table img_source
	 * @mbggenerated
	 */
	public ImgSource() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column img_source.id
	 * @return  the value of img_source.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column img_source.id
	 * @param id  the value for img_source.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column img_source.path
	 * @return  the value of img_source.path
	 * @mbggenerated
	 */
	public String getPath() {
		return path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column img_source.path
	 * @param path  the value for img_source.path
	 * @mbggenerated
	 */
	public void setPath(String path) {
		this.path = path == null ? null : path.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column img_source.create_time
	 * @return  the value of img_source.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column img_source.create_time
	 * @param createTime  the value for img_source.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}