package com.hd.domain;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table message
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Message implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column message.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * Database Column Remarks: 发送人id(0为系统) This field was generated by MyBatis Generator. This field corresponds to the database column message.sender_id
	 * @mbggenerated
	 */
	private String senderId;
	/**
	 * Database Column Remarks: 接收人id This field was generated by MyBatis Generator. This field corresponds to the database column message.receive_id
	 * @mbggenerated
	 */
	private String receiveId;
	/**
	 * Database Column Remarks: 消息状态 0-已发送(未查看) 1-已查看 2-已删除 This field was generated by MyBatis Generator. This field corresponds to the database column message.status
	 * @mbggenerated
	 */
	private String status;
	/**
	 * Database Column Remarks: 创建时间 This field was generated by MyBatis Generator. This field corresponds to the database column message.create_time
	 * @mbggenerated
	 */
	private Date createTime;
	/**
	 * Database Column Remarks: 发送内容 This field was generated by MyBatis Generator. This field corresponds to the database column message.content
	 * @mbggenerated
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table message
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message
	 * @mbggenerated
	 */
	public Message(String id, String senderId, String receiveId, String status,
			Date createTime, String content) {
		this.id = id;
		this.senderId = senderId;
		this.receiveId = receiveId;
		this.status = status;
		this.createTime = createTime;
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message
	 * @mbggenerated
	 */
	public Message() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column message.id
	 * @return  the value of message.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message.id
	 * @param id  the value for message.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column message.sender_id
	 * @return  the value of message.sender_id
	 * @mbggenerated
	 */
	public String getSenderId() {
		return senderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message.sender_id
	 * @param senderId  the value for message.sender_id
	 * @mbggenerated
	 */
	public void setSenderId(String senderId) {
		this.senderId = senderId == null ? null : senderId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column message.receive_id
	 * @return  the value of message.receive_id
	 * @mbggenerated
	 */
	public String getReceiveId() {
		return receiveId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message.receive_id
	 * @param receiveId  the value for message.receive_id
	 * @mbggenerated
	 */
	public void setReceiveId(String receiveId) {
		this.receiveId = receiveId == null ? null : receiveId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column message.status
	 * @return  the value of message.status
	 * @mbggenerated
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message.status
	 * @param status  the value for message.status
	 * @mbggenerated
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column message.create_time
	 * @return  the value of message.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message.create_time
	 * @param createTime  the value for message.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column message.content
	 * @return  the value of message.content
	 * @mbggenerated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message.content
	 * @param content  the value for message.content
	 * @mbggenerated
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}
}