package com.hd.domain;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class Question implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column question.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * Database Column Remarks: 提问用户id This field was generated by MyBatis Generator. This field corresponds to the database column question.user_id
	 * @mbggenerated
	 */
	private String userId;
	/**
	 * Database Column Remarks: 创建时间 This field was generated by MyBatis Generator. This field corresponds to the database column question.create_time
	 * @mbggenerated
	 */
	private Date createTime;
	/**
	 * Database Column Remarks: 问题内容 This field was generated by MyBatis Generator. This field corresponds to the database column question.content
	 * @mbggenerated
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table question
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;
	
	/** 手动添加的属性 */
	private String createTimeStr;
	
	private List<QuestionAnswer> questionAnswers;
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table question
	 * @mbggenerated
	 */
	public Question(String id, String userId, Date createTime, String content) {
		this.id = id;
		this.userId = userId;
		this.createTime = createTime;
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table question
	 * @mbggenerated
	 */
	public Question() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column question.id
	 * @return  the value of question.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column question.id
	 * @param id  the value for question.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column question.user_id
	 * @return  the value of question.user_id
	 * @mbggenerated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column question.user_id
	 * @param userId  the value for question.user_id
	 * @mbggenerated
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column question.create_time
	 * @return  the value of question.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column question.create_time
	 * @param createTime  the value for question.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column question.content
	 * @return  the value of question.content
	 * @mbggenerated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column question.content
	 * @param content  the value for question.content
	 * @mbggenerated
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	public String getCreateTimeStr() {
		return createTimeStr;
	}

	public void setCreateTimeStr(String createTimeStr) {
		this.createTimeStr = createTimeStr;
	}

	public List<QuestionAnswer> getQuestionAnswers() {
		return questionAnswers;
	}

	public void setQuestionAnswers(List<QuestionAnswer> questionAnswers) {
		this.questionAnswers = questionAnswers;
	}
}