package com.hd.domain;

import java.io.Serializable;
import java.util.Date;

public class QuestionAnswer implements Serializable {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column question_answer.id
	 * @mbggenerated
	 */
	private String id;

	/**
	 * Database Column Remarks: 回答用户id This field was generated by MyBatis Generator. This field corresponds to the database column question_answer.user_id
	 * @mbggenerated
	 */
	private String userId;

	/**
	 * Database Column Remarks: 问题id This field was generated by MyBatis Generator. This field corresponds to the database column question_answer.question_id
	 * @mbggenerated
	 */
	private String questionId;

	/**
	 * Database Column Remarks: 回答时间 This field was generated by MyBatis Generator. This field corresponds to the database column question_answer.create_time
	 * @mbggenerated
	 */
	private Date createTime;

	/**
	 * Database Column Remarks: 回答内容 This field was generated by MyBatis Generator. This field corresponds to the database column question_answer.answer_content
	 * @mbggenerated
	 */
	private String answerContent;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table question_answer
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table question_answer
	 * @mbggenerated
	 */
	public QuestionAnswer(String id, String userId, String questionId,
			Date createTime, String answerContent) {
		this.id = id;
		this.userId = userId;
		this.questionId = questionId;
		this.createTime = createTime;
		this.answerContent = answerContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table question_answer
	 * @mbggenerated
	 */
	public QuestionAnswer() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column question_answer.id
	 * @return  the value of question_answer.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column question_answer.id
	 * @param id  the value for question_answer.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column question_answer.user_id
	 * @return  the value of question_answer.user_id
	 * @mbggenerated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column question_answer.user_id
	 * @param userId  the value for question_answer.user_id
	 * @mbggenerated
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column question_answer.question_id
	 * @return  the value of question_answer.question_id
	 * @mbggenerated
	 */
	public String getQuestionId() {
		return questionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column question_answer.question_id
	 * @param questionId  the value for question_answer.question_id
	 * @mbggenerated
	 */
	public void setQuestionId(String questionId) {
		this.questionId = questionId == null ? null : questionId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column question_answer.create_time
	 * @return  the value of question_answer.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column question_answer.create_time
	 * @param createTime  the value for question_answer.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column question_answer.answer_content
	 * @return  the value of question_answer.answer_content
	 * @mbggenerated
	 */
	public String getAnswerContent() {
		return answerContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column question_answer.answer_content
	 * @param answerContent  the value for question_answer.answer_content
	 * @mbggenerated
	 */
	public void setAnswerContent(String answerContent) {
		this.answerContent = answerContent == null ? null : answerContent
				.trim();
	}

}