package com.hd.domain;

import java.io.Serializable;

public class SysCompany implements Serializable {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_company.id
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * Database Column Remarks: 公司名称 This field was generated by MyBatis Generator. This field corresponds to the database column sys_company.name
	 * @mbggenerated
	 */
	private String name;

	/**
	 * Database Column Remarks: 公司地址 This field was generated by MyBatis Generator. This field corresponds to the database column sys_company.address
	 * @mbggenerated
	 */
	private String address;

	/**
	 * Database Column Remarks: 公司电话 This field was generated by MyBatis Generator. This field corresponds to the database column sys_company.phone
	 * @mbggenerated
	 */
	private String phone;

	/**
	 * Database Column Remarks: 公司banner图片id This field was generated by MyBatis Generator. This field corresponds to the database column sys_company.banner_img
	 * @mbggenerated
	 */
	private String bannerImg;

	/**
	 * Database Column Remarks: 公司logo图片id This field was generated by MyBatis Generator. This field corresponds to the database column sys_company.logo_img
	 * @mbggenerated
	 */
	private String logoImg;

	/**
	 * Database Column Remarks: 公司营业执照图片id This field was generated by MyBatis Generator. This field corresponds to the database column sys_company.qualifications_img
	 * @mbggenerated
	 */
	private String qualificationsImg;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_company
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_company
	 * @mbggenerated
	 */
	public SysCompany(Integer id, String name, String address, String phone,
			String bannerImg, String logoImg, String qualificationsImg) {
		this.id = id;
		this.name = name;
		this.address = address;
		this.phone = phone;
		this.bannerImg = bannerImg;
		this.logoImg = logoImg;
		this.qualificationsImg = qualificationsImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_company
	 * @mbggenerated
	 */
	public SysCompany() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_company.id
	 * @return  the value of sys_company.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_company.id
	 * @param id  the value for sys_company.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_company.name
	 * @return  the value of sys_company.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_company.name
	 * @param name  the value for sys_company.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_company.address
	 * @return  the value of sys_company.address
	 * @mbggenerated
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_company.address
	 * @param address  the value for sys_company.address
	 * @mbggenerated
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_company.phone
	 * @return  the value of sys_company.phone
	 * @mbggenerated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_company.phone
	 * @param phone  the value for sys_company.phone
	 * @mbggenerated
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_company.banner_img
	 * @return  the value of sys_company.banner_img
	 * @mbggenerated
	 */
	public String getBannerImg() {
		return bannerImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_company.banner_img
	 * @param bannerImg  the value for sys_company.banner_img
	 * @mbggenerated
	 */
	public void setBannerImg(String bannerImg) {
		this.bannerImg = bannerImg == null ? null : bannerImg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_company.logo_img
	 * @return  the value of sys_company.logo_img
	 * @mbggenerated
	 */
	public String getLogoImg() {
		return logoImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_company.logo_img
	 * @param logoImg  the value for sys_company.logo_img
	 * @mbggenerated
	 */
	public void setLogoImg(String logoImg) {
		this.logoImg = logoImg == null ? null : logoImg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_company.qualifications_img
	 * @return  the value of sys_company.qualifications_img
	 * @mbggenerated
	 */
	public String getQualificationsImg() {
		return qualificationsImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_company.qualifications_img
	 * @param qualificationsImg  the value for sys_company.qualifications_img
	 * @mbggenerated
	 */
	public void setQualificationsImg(String qualificationsImg) {
		this.qualificationsImg = qualificationsImg == null ? null
				: qualificationsImg.trim();
	}

}