package com.hd.domain;

import java.io.Serializable;

public class SysCompanyWithBLOBs extends SysCompany implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.company_introduce
     *
     * @mbg.generated
     */
    private String companyIntroduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.service_area
     *
     * @mbg.generated
     */
    private String serviceArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_company
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbg.generated
     */
    public SysCompanyWithBLOBs(Integer id, String name, String address, String phone, String bannerImg, String logoImg, String qualificationsImg, String companyIntroduce, String serviceArea) {
        super(id, name, address, phone, bannerImg, logoImg, qualificationsImg);
        this.companyIntroduce = companyIntroduce;
        this.serviceArea = serviceArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbg.generated
     */
    public SysCompanyWithBLOBs() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.company_introduce
     *
     * @return the value of sys_company.company_introduce
     *
     * @mbg.generated
     */
    public String getCompanyIntroduce() {
        return companyIntroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.company_introduce
     *
     * @param companyIntroduce the value for sys_company.company_introduce
     *
     * @mbg.generated
     */
    public void setCompanyIntroduce(String companyIntroduce) {
        this.companyIntroduce = companyIntroduce == null ? null : companyIntroduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.service_area
     *
     * @return the value of sys_company.service_area
     *
     * @mbg.generated
     */
    public String getServiceArea() {
        return serviceArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.service_area
     *
     * @param serviceArea the value for sys_company.service_area
     *
     * @mbg.generated
     */
    public void setServiceArea(String serviceArea) {
        this.serviceArea = serviceArea == null ? null : serviceArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysCompanyWithBLOBs other = (SysCompanyWithBLOBs) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
            && (this.getBannerImg() == null ? other.getBannerImg() == null : this.getBannerImg().equals(other.getBannerImg()))
            && (this.getLogoImg() == null ? other.getLogoImg() == null : this.getLogoImg().equals(other.getLogoImg()))
            && (this.getQualificationsImg() == null ? other.getQualificationsImg() == null : this.getQualificationsImg().equals(other.getQualificationsImg()))
            && (this.getCompanyIntroduce() == null ? other.getCompanyIntroduce() == null : this.getCompanyIntroduce().equals(other.getCompanyIntroduce()))
            && (this.getServiceArea() == null ? other.getServiceArea() == null : this.getServiceArea().equals(other.getServiceArea()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result + ((getBannerImg() == null) ? 0 : getBannerImg().hashCode());
        result = prime * result + ((getLogoImg() == null) ? 0 : getLogoImg().hashCode());
        result = prime * result + ((getQualificationsImg() == null) ? 0 : getQualificationsImg().hashCode());
        result = prime * result + ((getCompanyIntroduce() == null) ? 0 : getCompanyIntroduce().hashCode());
        result = prime * result + ((getServiceArea() == null) ? 0 : getServiceArea().hashCode());
        return result;
    }
}