package com.hd.domain;

import java.io.Serializable;

public class SysCompanyWithBLOBs extends SysCompany implements Serializable {
    /**
	 * Database Column Remarks: 公司简介 This field was generated by MyBatis Generator. This field corresponds to the database column sys_company.company_introduce
	 * @mbggenerated
	 */
	private String companyIntroduce;

	/**
	 * Database Column Remarks: 服务地区 This field was generated by MyBatis Generator. This field corresponds to the database column sys_company.service_area
	 * @mbggenerated
	 */
	private String serviceArea;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_company
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_company
	 * @mbggenerated
	 */
	public SysCompanyWithBLOBs(Integer id, String name, String address,
			String phone, String bannerImg, String logoImg,
			String qualificationsImg, String companyIntroduce,
			String serviceArea) {
		super(id, name, address, phone, bannerImg, logoImg, qualificationsImg);
		this.companyIntroduce = companyIntroduce;
		this.serviceArea = serviceArea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_company
	 * @mbggenerated
	 */
	public SysCompanyWithBLOBs() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_company.company_introduce
	 * @return  the value of sys_company.company_introduce
	 * @mbggenerated
	 */
	public String getCompanyIntroduce() {
		return companyIntroduce;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_company.company_introduce
	 * @param companyIntroduce  the value for sys_company.company_introduce
	 * @mbggenerated
	 */
	public void setCompanyIntroduce(String companyIntroduce) {
		this.companyIntroduce = companyIntroduce == null ? null
				: companyIntroduce.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_company.service_area
	 * @return  the value of sys_company.service_area
	 * @mbggenerated
	 */
	public String getServiceArea() {
		return serviceArea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_company.service_area
	 * @param serviceArea  the value for sys_company.service_area
	 * @mbggenerated
	 */
	public void setServiceArea(String serviceArea) {
		this.serviceArea = serviceArea == null ? null : serviceArea.trim();
	}

}