package com.hd.domain;

import java.io.Serializable;

public class SysCompany implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.banner_img
     *
     * @mbg.generated
     */
    private String bannerImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.logo_img
     *
     * @mbg.generated
     */
    private String logoImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.qualifications_img
     *
     * @mbg.generated
     */
    private String qualificationsImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_company
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbg.generated
     */
    public SysCompany(Integer id, String name, String address, String phone, String bannerImg, String logoImg, String qualificationsImg) {
        this.id = id;
        this.name = name;
        this.address = address;
        this.phone = phone;
        this.bannerImg = bannerImg;
        this.logoImg = logoImg;
        this.qualificationsImg = qualificationsImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbg.generated
     */
    public SysCompany() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.id
     *
     * @return the value of sys_company.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.id
     *
     * @param id the value for sys_company.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.name
     *
     * @return the value of sys_company.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.name
     *
     * @param name the value for sys_company.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.address
     *
     * @return the value of sys_company.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.address
     *
     * @param address the value for sys_company.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.phone
     *
     * @return the value of sys_company.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.phone
     *
     * @param phone the value for sys_company.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.banner_img
     *
     * @return the value of sys_company.banner_img
     *
     * @mbg.generated
     */
    public String getBannerImg() {
        return bannerImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.banner_img
     *
     * @param bannerImg the value for sys_company.banner_img
     *
     * @mbg.generated
     */
    public void setBannerImg(String bannerImg) {
        this.bannerImg = bannerImg == null ? null : bannerImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.logo_img
     *
     * @return the value of sys_company.logo_img
     *
     * @mbg.generated
     */
    public String getLogoImg() {
        return logoImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.logo_img
     *
     * @param logoImg the value for sys_company.logo_img
     *
     * @mbg.generated
     */
    public void setLogoImg(String logoImg) {
        this.logoImg = logoImg == null ? null : logoImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.qualifications_img
     *
     * @return the value of sys_company.qualifications_img
     *
     * @mbg.generated
     */
    public String getQualificationsImg() {
        return qualificationsImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.qualifications_img
     *
     * @param qualificationsImg the value for sys_company.qualifications_img
     *
     * @mbg.generated
     */
    public void setQualificationsImg(String qualificationsImg) {
        this.qualificationsImg = qualificationsImg == null ? null : qualificationsImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysCompany other = (SysCompany) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
            && (this.getBannerImg() == null ? other.getBannerImg() == null : this.getBannerImg().equals(other.getBannerImg()))
            && (this.getLogoImg() == null ? other.getLogoImg() == null : this.getLogoImg().equals(other.getLogoImg()))
            && (this.getQualificationsImg() == null ? other.getQualificationsImg() == null : this.getQualificationsImg().equals(other.getQualificationsImg()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result + ((getBannerImg() == null) ? 0 : getBannerImg().hashCode());
        result = prime * result + ((getLogoImg() == null) ? 0 : getLogoImg().hashCode());
        result = prime * result + ((getQualificationsImg() == null) ? 0 : getQualificationsImg().hashCode());
        return result;
    }
}