package com.hd.domain;

import java.io.Serializable;
import java.util.Date;

public class SysExperienceList implements Serializable {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_experience_list.id
	 * @mbggenerated
	 */
	private String id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_experience_list.title
	 * @mbggenerated
	 */
	private String title;

	/**
	 * Database Column Remarks: 经验状态 0-正常 1-删除 This field was generated by MyBatis Generator. This field corresponds to the database column sys_experience_list.status
	 * @mbggenerated
	 */
	private String status;

	/**
	 * Database Column Remarks: 创建时间 This field was generated by MyBatis Generator. This field corresponds to the database column sys_experience_list.create_time
	 * @mbggenerated
	 */
	private Date createTime;

	/**
	 * Database Column Remarks: 经验内容 This field was generated by MyBatis Generator. This field corresponds to the database column sys_experience_list.content
	 * @mbggenerated
	 */
	private String content;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_experience_list
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	private String createTimeStr;
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_experience_list
	 * @mbggenerated
	 */
	public SysExperienceList(String id, String title, String status,
			Date createTime, String content) {
		this.id = id;
		this.title = title;
		this.status = status;
		this.createTime = createTime;
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_experience_list
	 * @mbggenerated
	 */
	public SysExperienceList() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_experience_list.id
	 * @return  the value of sys_experience_list.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_experience_list.id
	 * @param id  the value for sys_experience_list.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_experience_list.title
	 * @return  the value of sys_experience_list.title
	 * @mbggenerated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_experience_list.title
	 * @param title  the value for sys_experience_list.title
	 * @mbggenerated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_experience_list.status
	 * @return  the value of sys_experience_list.status
	 * @mbggenerated
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_experience_list.status
	 * @param status  the value for sys_experience_list.status
	 * @mbggenerated
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_experience_list.create_time
	 * @return  the value of sys_experience_list.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_experience_list.create_time
	 * @param createTime  the value for sys_experience_list.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_experience_list.content
	 * @return  the value of sys_experience_list.content
	 * @mbggenerated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_experience_list.content
	 * @param content  the value for sys_experience_list.content
	 * @mbggenerated
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	public String getCreateTimeStr() {
		return createTimeStr;
	}

	public void setCreateTimeStr(String createTimeStr) {
		this.createTimeStr = createTimeStr;
	}
}