package com.hd.domain;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_menu
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class SysMenu implements Serializable {

	/**
	 * Database Column Remarks: 菜单id This field was generated by MyBatis Generator. This field corresponds to the database column sys_menu.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * Database Column Remarks: 父菜单id This field was generated by MyBatis Generator. This field corresponds to the database column sys_menu.parent_id
	 * @mbggenerated
	 */
	private String parentId;
	/**
	 * Database Column Remarks: 菜单名 This field was generated by MyBatis Generator. This field corresponds to the database column sys_menu.title
	 * @mbggenerated
	 */
	private String title;
	/**
	 * Database Column Remarks: 图标 This field was generated by MyBatis Generator. This field corresponds to the database column sys_menu.icon
	 * @mbggenerated
	 */
	private String icon;
	/**
	 * Database Column Remarks: 菜单url This field was generated by MyBatis Generator. This field corresponds to the database column sys_menu.url
	 * @mbggenerated
	 */
	private String url;
	/**
	 * Database Column Remarks: 菜单状态 0-正常 1-废弃 This field was generated by MyBatis Generator. This field corresponds to the database column sys_menu.status
	 * @mbggenerated
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_menu
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbggenerated
	 */
	public SysMenu(String id, String parentId, String title, String icon,
			String url, Integer status) {
		this.id = id;
		this.parentId = parentId;
		this.title = title;
		this.icon = icon;
		this.url = url;
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbggenerated
	 */
	public SysMenu() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_menu.id
	 * @return  the value of sys_menu.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_menu.id
	 * @param id  the value for sys_menu.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_menu.parent_id
	 * @return  the value of sys_menu.parent_id
	 * @mbggenerated
	 */
	public String getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_menu.parent_id
	 * @param parentId  the value for sys_menu.parent_id
	 * @mbggenerated
	 */
	public void setParentId(String parentId) {
		this.parentId = parentId == null ? null : parentId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_menu.title
	 * @return  the value of sys_menu.title
	 * @mbggenerated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_menu.title
	 * @param title  the value for sys_menu.title
	 * @mbggenerated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_menu.icon
	 * @return  the value of sys_menu.icon
	 * @mbggenerated
	 */
	public String getIcon() {
		return icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_menu.icon
	 * @param icon  the value for sys_menu.icon
	 * @mbggenerated
	 */
	public void setIcon(String icon) {
		this.icon = icon == null ? null : icon.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_menu.url
	 * @return  the value of sys_menu.url
	 * @mbggenerated
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_menu.url
	 * @param url  the value for sys_menu.url
	 * @mbggenerated
	 */
	public void setUrl(String url) {
		this.url = url == null ? null : url.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_menu.status
	 * @return  the value of sys_menu.status
	 * @mbggenerated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_menu.status
	 * @param status  the value for sys_menu.status
	 * @mbggenerated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}
}