package com.hd.domain;

import java.io.Serializable;
import java.util.Date;

public class SysPreferentialActivities implements Serializable {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_preferential_activities.id
	 * @mbggenerated
	 */
	private String id;

	/**
	 * Database Column Remarks: 活动标题 This field was generated by MyBatis Generator. This field corresponds to the database column sys_preferential_activities.titile
	 * @mbggenerated
	 */
	private String titile;

	/**
	 * Database Column Remarks: 经验状态 0-正常 1-删除 This field was generated by MyBatis Generator. This field corresponds to the database column sys_preferential_activities.status
	 * @mbggenerated
	 */
	private String status;

	/**
	 * Database Column Remarks: 创建时间 This field was generated by MyBatis Generator. This field corresponds to the database column sys_preferential_activities.create_time
	 * @mbggenerated
	 */
	private Date createTime;

	/**
	 * Database Column Remarks: 活动内容 This field was generated by MyBatis Generator. This field corresponds to the database column sys_preferential_activities.content
	 * @mbggenerated
	 */
	private String content;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_preferential_activities
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_preferential_activities
	 * @mbggenerated
	 */
	public SysPreferentialActivities(String id, String titile, String status,
			Date createTime, String content) {
		this.id = id;
		this.titile = titile;
		this.status = status;
		this.createTime = createTime;
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_preferential_activities
	 * @mbggenerated
	 */
	public SysPreferentialActivities() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_preferential_activities.id
	 * @return  the value of sys_preferential_activities.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_preferential_activities.id
	 * @param id  the value for sys_preferential_activities.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_preferential_activities.titile
	 * @return  the value of sys_preferential_activities.titile
	 * @mbggenerated
	 */
	public String getTitile() {
		return titile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_preferential_activities.titile
	 * @param titile  the value for sys_preferential_activities.titile
	 * @mbggenerated
	 */
	public void setTitile(String titile) {
		this.titile = titile == null ? null : titile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_preferential_activities.status
	 * @return  the value of sys_preferential_activities.status
	 * @mbggenerated
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_preferential_activities.status
	 * @param status  the value for sys_preferential_activities.status
	 * @mbggenerated
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_preferential_activities.create_time
	 * @return  the value of sys_preferential_activities.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_preferential_activities.create_time
	 * @param createTime  the value for sys_preferential_activities.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_preferential_activities.content
	 * @return  the value of sys_preferential_activities.content
	 * @mbggenerated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_preferential_activities.content
	 * @param content  the value for sys_preferential_activities.content
	 * @mbggenerated
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

}