package com.hd.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class User implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * Database Column Remarks: 用户名 This field was generated by MyBatis Generator. This field corresponds to the database column user.user_name
	 * @mbggenerated
	 */
	private String userName;
	/**
	 * Database Column Remarks: 性别 0-男 1-女 This field was generated by MyBatis Generator. This field corresponds to the database column user.sex
	 * @mbggenerated
	 */
	private Integer sex;
	/**
	 * Database Column Remarks: 密码 This field was generated by MyBatis Generator. This field corresponds to the database column user.password
	 * @mbggenerated
	 */
	private String password;
	/**
	 * Database Column Remarks: 手机号码 This field was generated by MyBatis Generator. This field corresponds to the database column user.telphone
	 * @mbggenerated
	 */
	private String telphone;
	/**
	 * Database Column Remarks: 头像 This field was generated by MyBatis Generator. This field corresponds to the database column user.avatar
	 * @mbggenerated
	 */
	private String avatar;
	/**
	 * Database Column Remarks: 用户类型 0-商户 1-设计师 2-管理员 This field was generated by MyBatis Generator. This field corresponds to the database column user.type
	 * @mbggenerated
	 */
	private String type;
	/**
	 * Database Column Remarks: 职称(弃用) This field was generated by MyBatis Generator. This field corresponds to the database column user.positional_titles
	 * @mbggenerated
	 */
	private String positionalTitles;
	/**
	 * Database Column Remarks: 案例 (设计师已设计成功数量) This field was generated by MyBatis Generator. This field corresponds to the database column user.case_example
	 * @mbggenerated
	 */
	private BigDecimal caseExample;
	/**
	 * Database Column Remarks: 用户状态 0-正常 1-删除 This field was generated by MyBatis Generator. This field corresponds to the database column user.status
	 * @mbggenerated
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.create_time
	 * @mbggenerated
	 */
	private Date createTime;
	
	/**
	 * 确认密码
	 */
	private String repeat;
	
	private String avatarPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated
	 */
	public User(String id, String userName, Integer sex, String password,
			String telphone, String avatar, String type,
			String positionalTitles, BigDecimal caseExample, Integer status,
			Date createTime) {
		this.id = id;
		this.userName = userName;
		this.sex = sex;
		this.password = password;
		this.telphone = telphone;
		this.avatar = avatar;
		this.type = type;
		this.positionalTitles = positionalTitles;
		this.caseExample = caseExample;
		this.status = status;
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated
	 */
	public User() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
	 * @return  the value of user.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
	 * @param id  the value for user.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.user_name
	 * @return  the value of user.user_name
	 * @mbggenerated
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.user_name
	 * @param userName  the value for user.user_name
	 * @mbggenerated
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.sex
	 * @return  the value of user.sex
	 * @mbggenerated
	 */
	public Integer getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.sex
	 * @param sex  the value for user.sex
	 * @mbggenerated
	 */
	public void setSex(Integer sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbggenerated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @mbggenerated
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.telphone
	 * @return  the value of user.telphone
	 * @mbggenerated
	 */
	public String getTelphone() {
		return telphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.telphone
	 * @param telphone  the value for user.telphone
	 * @mbggenerated
	 */
	public void setTelphone(String telphone) {
		this.telphone = telphone == null ? null : telphone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.avatar
	 * @return  the value of user.avatar
	 * @mbggenerated
	 */
	public String getAvatar() {
		return avatar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.avatar
	 * @param avatar  the value for user.avatar
	 * @mbggenerated
	 */
	public void setAvatar(String avatar) {
		this.avatar = avatar == null ? null : avatar.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.type
	 * @return  the value of user.type
	 * @mbggenerated
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.type
	 * @param type  the value for user.type
	 * @mbggenerated
	 */
	public void setType(String type) {
		this.type = type == null ? null : type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.positional_titles
	 * @return  the value of user.positional_titles
	 * @mbggenerated
	 */
	public String getPositionalTitles() {
		return positionalTitles;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.positional_titles
	 * @param positionalTitles  the value for user.positional_titles
	 * @mbggenerated
	 */
	public void setPositionalTitles(String positionalTitles) {
		this.positionalTitles = positionalTitles == null ? null
				: positionalTitles.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.case_example
	 * @return  the value of user.case_example
	 * @mbggenerated
	 */
	public BigDecimal getCaseExample() {
		return caseExample;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.case_example
	 * @param caseExample  the value for user.case_example
	 * @mbggenerated
	 */
	public void setCaseExample(BigDecimal caseExample) {
		this.caseExample = caseExample;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.status
	 * @return  the value of user.status
	 * @mbggenerated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.status
	 * @param status  the value for user.status
	 * @mbggenerated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.create_time
	 * @return  the value of user.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.create_time
	 * @param createTime  the value for user.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getRepeat() {
		return repeat;
	}

	public void setRepeat(String repeat) {
		this.repeat = repeat;
	}

	public String getAvatarPath() {
		return avatarPath;
	}

	public void setAvatarPath(String avatarPath) {
		this.avatarPath = avatarPath;
	}
}