package com.hd.mapper;

import java.util.List;

import com.hd.domain.ApplyAttachment;

public interface ApplyAttachmentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply_attachment
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply_attachment
	 * @mbggenerated
	 */
	int insert(ApplyAttachment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply_attachment
	 * @mbggenerated
	 */
	int insertSelective(ApplyAttachment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply_attachment
	 * @mbggenerated
	 */
	ApplyAttachment selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply_attachment
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(ApplyAttachment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply_attachment
	 * @mbggenerated
	 */
	int updateByPrimaryKey(ApplyAttachment record);

	/**
	 * 按条件查询附件内容
	 * @param applyAttachment 条件参数对象
	 * @return
	 */
	List<ApplyAttachment> selectBySelective(ApplyAttachment applyAttachment);
}