package com.hd.mapper;

import java.util.List;

import com.hd.domain.ApplyRecord;

public interface ApplyRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_record
     *
     * @mbggenerated
     */
    int insert(ApplyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_record
     *
     * @mbggenerated
     */
    int insertSelective(ApplyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_record
     *
     * @mbggenerated
     */
    ApplyRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ApplyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ApplyRecord record);
    
    /**
     * 按条件查询申请记录
     * @return
     */
    List<ApplyRecord> selectBySelective(ApplyRecord record);
    
    /**
     * 按条件更新申请记录
     * @param record
     * @return
     */
    int updateSelectiveByApplyId(ApplyRecord record);
}