package com.hd.mapper;

import com.hd.domain.DecorationEffectKey;

public interface DecorationEffectKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_effect_key
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_effect_key
     *
     * @mbg.generated
     */
    int insert(DecorationEffectKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_effect_key
     *
     * @mbg.generated
     */
    int insertSelective(DecorationEffectKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_effect_key
     *
     * @mbg.generated
     */
    DecorationEffectKey selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_effect_key
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DecorationEffectKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_effect_key
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DecorationEffectKey record);
}