package com.hd.mapper;

import java.util.HashMap;
import java.util.List;

import com.hd.domain.BasePage;
import com.hd.domain.DecorationEffect;
import com.hd.domain.Result;

public interface DecorationEffectMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_effect
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_effect
	 * @mbggenerated
	 */
	int insert(DecorationEffect record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_effect
	 * @mbggenerated
	 */
	int insertSelective(DecorationEffect record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_effect
	 * @mbggenerated
	 */
	DecorationEffect selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_effect
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(DecorationEffect record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_effect
	 * @mbggenerated
	 */
	int updateByPrimaryKey(DecorationEffect record);

    /**
     * 查询装修效果列表
     * @param basePage 查询记录参数
     * @return
     */
    List<HashMap<String, Object>> queryDecorationEffectLis(BasePage basePage);
    
    /**
     * 统计所有的装修效果记录
     * @return
     */
    int countAllDecorEffect();
}