package com.hd.mapper;

import com.hd.domain.DecorationApply;

public interface DecorationApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_apply
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_apply
     *
     * @mbg.generated
     */
    int insert(DecorationApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_apply
     *
     * @mbg.generated
     */
    int insertSelective(DecorationApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_apply
     *
     * @mbg.generated
     */
    DecorationApply selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_apply
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DecorationApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_apply
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DecorationApply record);
}