package com.hd.mapper;

import com.hd.domain.DecorationStyle;

public interface DecorationStyleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_style
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_style
     *
     * @mbg.generated
     */
    int insert(DecorationStyle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_style
     *
     * @mbg.generated
     */
    int insertSelective(DecorationStyle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_style
     *
     * @mbg.generated
     */
    DecorationStyle selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_style
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DecorationStyle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_style
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DecorationStyle record);
}