package com.hd.mapper;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.hd.domain.BasePage;
import com.hd.domain.DecorationApply;

public interface DecorationApplyMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_apply
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_apply
	 * @mbggenerated
	 */
	int insert(DecorationApply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_apply
	 * @mbggenerated
	 */
	int insertSelective(DecorationApply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_apply
	 * @mbggenerated
	 */
	DecorationApply selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_apply
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(DecorationApply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_apply
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(DecorationApply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_apply
	 * @mbggenerated
	 */
	int updateByPrimaryKey(DecorationApply record);

	/**
     * 查询装修列表
     * @param queryAll
     * @return
     */
    List<HashMap<String,Object>> queryDecorationApplyLis(@Param("queryAll")boolean queryAll, @Param("number")int number);
    
    /**
     * 查询用户的装修申�?
     * @param decorationApply
     * @return
     */
    List<DecorationApply> queryDecorationApplyBySelective(DecorationApply decorationApply);
    
    /**
     * 查询装修申请审核列表
     * @param decorationApply
     * @return
     */
    List<DecorationApply> queryDecorationApplyCheckLis(DecorationApply decorationApply);
    
    /**
     * 查询用户审核通过的装修申请列表
     * @param userId 用户id
     * @return
     */
    List<DecorationApply> selectByUserId(String userId);
     
    /**
     * 查询申请设计列表
     * @param basePage
     * @param designerId 设计师id
     * @return
     */
    List<DecorationApply> queryApplyDesignLis(@Param("basePage")BasePage basePage, @Param("designerId")String designerId);
    
    /**
     * 查询设计师设计列表
     * @param designerId
     * @return
     */
    List<DecorationApply> queryDesignLis(String designerId);
    
    /**
     * 查询装修申请基本信息
     * @param decorationApply
     * @return
     */
    List<DecorationApply> queryBaseBySelective(DecorationApply decorationApply);
}