package com.hd.mapper;

import java.util.List;

import com.hd.domain.DecorationEffectKey;

public interface DecorationEffectKeyMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_effect_key
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_effect_key
	 * @mbggenerated
	 */
	int insert(DecorationEffectKey record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_effect_key
	 * @mbggenerated
	 */
	int insertSelective(DecorationEffectKey record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_effect_key
	 * @mbggenerated
	 */
	DecorationEffectKey selectByPrimaryKey(String id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_effect_key
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(DecorationEffectKey record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_effect_key
	 * @mbggenerated
	 */
	int updateByPrimaryKey(DecorationEffectKey record);
	/**
	 * 
	 * @param effectId
	 * @return
	 */
	DecorationEffectKey queryDecEffect(String effectId);
    /**
     * 通过效果图表id查询效果关键字
     * @param effectId 效果图表id
     * @return
     */
    List<DecorationEffectKey> queryKeyByEffectId(String effectId);
}