package com.hd.mapper;

import java.util.List;

import com.hd.domain.DecorationStyle;

public interface DecorationStyleMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_style
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_style
	 * @mbggenerated
	 */
	int insert(DecorationStyle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_style
	 * @mbggenerated
	 */
	int insertSelective(DecorationStyle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_style
	 * @mbggenerated
	 */
	DecorationStyle selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_style
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(DecorationStyle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_style
	 * @mbggenerated
	 */
	int updateByPrimaryKey(DecorationStyle record);
	
	/**
	 * 查询所有装修风格内容
	 * @return
	 */
	List<DecorationStyle> queryAll();
}