package com.hd.mapper;

import com.hd.domain.DecorationEffect;

public interface DecorationEffectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_effect
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_effect
     *
     * @mbg.generated
     */
    int insert(DecorationEffect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_effect
     *
     * @mbg.generated
     */
    int insertSelective(DecorationEffect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_effect
     *
     * @mbg.generated
     */
    DecorationEffect selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_effect
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DecorationEffect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_effect
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DecorationEffect record);
}