package com.hd.mapper;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.hd.domain.DecorationEffect;

public interface DecorationEffectMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_effect
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_effect
	 * @mbggenerated
	 */
	int insert(DecorationEffect record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_effect
	 * @mbggenerated
	 */
	int insertSelective(DecorationEffect record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_effect
	 * @mbggenerated
	 */
	DecorationEffect selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_effect
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(DecorationEffect record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_effect
	 * @mbggenerated
	 */
	int updateByPrimaryKey(DecorationEffect record);

    /**
     * 查询装修效果列表
     * @param start 查询记录开始条数
     * @param end 查询记录结束条数
     * @return
     */
    List<HashMap<String, Object>> queryDecorationEffectLis(@Param("start")int start, @Param("end")int end);
}