package com.hd.mapper;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.hd.domain.DecorationApply;

public interface DecorationApplyMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_apply
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_apply
	 * @mbggenerated
	 */
	int insert(DecorationApply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_apply
	 * @mbggenerated
	 */
	int insertSelective(DecorationApply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_apply
	 * @mbggenerated
	 */
	DecorationApply selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_apply
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(DecorationApply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table decoration_apply
	 * @mbggenerated
	 */
	int updateByPrimaryKey(DecorationApply record);

	/**
     * 查询装修列表
     * @param queryAll
     * @return
     */
    List<HashMap<String,Object>> queryDecorationApplyLis(@Param("queryAll")boolean queryAll, @Param("number")int number);
    
    /**
     * 查询用户的装修申�?
     * @param userId 用户id
     * @return
     */
    List<DecorationApply> queryDecorationApply(String userId);
    
}