package com.hd.mapper;

import com.hd.domain.DesignerStyle;

public interface DesignerStyleMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table designer_style
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table designer_style
	 * @mbggenerated
	 */
	int insert(DesignerStyle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table designer_style
	 * @mbggenerated
	 */
	int insertSelective(DesignerStyle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table designer_style
	 * @mbggenerated
	 */
	DesignerStyle selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table designer_style
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(DesignerStyle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table designer_style
	 * @mbggenerated
	 */
	int updateByPrimaryKey(DesignerStyle record);

}