package com.hd.mapper;

import com.hd.domain.DesignerStyle;

public interface DesignerStyleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table designer_style
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table designer_style
     *
     * @mbg.generated
     */
    int insert(DesignerStyle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table designer_style
     *
     * @mbg.generated
     */
    int insertSelective(DesignerStyle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table designer_style
     *
     * @mbg.generated
     */
    DesignerStyle selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table designer_style
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DesignerStyle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table designer_style
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DesignerStyle record);
}