package com.hd.mapper;

import java.util.List;

import com.hd.domain.DesignerStyle;
import com.hd.domain.DesignerStyleInfo;

public interface DesignerStyleMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table designer_style
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table designer_style
	 * @mbggenerated
	 */
	int insert(DesignerStyle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table designer_style
	 * @mbggenerated
	 */
	int insertSelective(DesignerStyle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table designer_style
	 * @mbggenerated
	 */
	DesignerStyle selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table designer_style
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(DesignerStyle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table designer_style
	 * @mbggenerated
	 */
	int updateByPrimaryKey(DesignerStyle record);
	
	/**
	 * 查询设计师风格
	 * @param designerId 设计师id
	 * @return
	 */
	List<DesignerStyleInfo> queryStyles(String designerId);
	
	/**
	 * 查询所有的风格与设计师对应的状态 
	 * @param designerId 设计师id
	 * @return
	 */
	List<DesignerStyleInfo> queryAllStyleStatus(String designerId);

}