package com.hd.mapper;

import com.hd.domain.ImgSource;

public interface ImgSourceMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table img_source
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table img_source
	 * @mbggenerated
	 */
	int insert(ImgSource record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table img_source
	 * @mbggenerated
	 */
	int insertSelective(ImgSource record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table img_source
	 * @mbggenerated
	 */
	ImgSource selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table img_source
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(ImgSource record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table img_source
	 * @mbggenerated
	 */
	int updateByPrimaryKey(ImgSource record);

}