package com.hd.mapper;

import com.hd.domain.ImgSource;

public interface ImgSourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img_source
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img_source
     *
     * @mbg.generated
     */
    int insert(ImgSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img_source
     *
     * @mbg.generated
     */
    int insertSelective(ImgSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img_source
     *
     * @mbg.generated
     */
    ImgSource selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img_source
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ImgSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img_source
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ImgSource record);
}