package com.hd.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.hd.domain.BasePage;
import com.hd.domain.Message;

public interface MessageMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message
	 * @mbggenerated
	 */
	int insert(Message record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message
	 * @mbggenerated
	 */
	int insertSelective(Message record);
	
	int updateByPrimaryKeySelective(Message record);

	/**
     * 查询用户消息列表
     * @param receiveId 接收者id
     * @return
     */
    List<Message> selectMsgList(@Param("receiveId")String receiveId, @Param("basePage")BasePage basePage);
    
    /**
     * 统计消息总数
     * @param userId 用户id
     * @return
     */
    int countMyMsg(String userId);
}