package com.hd.mapper;

import com.hd.domain.QuestionAnswer;

public interface QuestionAnswerMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table question_answer
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table question_answer
	 * @mbggenerated
	 */
	int insert(QuestionAnswer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table question_answer
	 * @mbggenerated
	 */
	int insertSelective(QuestionAnswer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table question_answer
	 * @mbggenerated
	 */
	QuestionAnswer selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table question_answer
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(QuestionAnswer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table question_answer
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(QuestionAnswer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table question_answer
	 * @mbggenerated
	 */
	int updateByPrimaryKey(QuestionAnswer record);

}