package com.hd.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.hd.domain.BasePage;
import com.hd.domain.Question;
import com.hd.domain.QuestionAndAnswerVO;

public interface QuestionMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table question
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table question
	 * @mbggenerated
	 */
	int insert(Question record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table question
	 * @mbggenerated
	 */
	int insertSelective(Question record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table question
	 * @mbggenerated
	 */
	Question selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table question
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Question record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table question
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(Question record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table question
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Question record);

	/**
     * 查询主页问题问答信息
     * @param basePage 分页对象
     * @return
     */
    List<QuestionAndAnswerVO> queryQuestionAndAnswer(BasePage basePage);
    
}