package com.hd.mapper;

import com.hd.domain.SysCompany;
import com.hd.domain.SysCompanyWithBLOBs;

public interface SysCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbg.generated
     */
    int insert(SysCompanyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbg.generated
     */
    int insertSelective(SysCompanyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbg.generated
     */
    SysCompanyWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysCompanyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(SysCompanyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysCompany record);
}