package com.hd.mapper;

import com.hd.domain.SysExperienceList;

public interface SysExperienceListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_experience_list
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_experience_list
     *
     * @mbg.generated
     */
    int insert(SysExperienceList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_experience_list
     *
     * @mbg.generated
     */
    int insertSelective(SysExperienceList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_experience_list
     *
     * @mbg.generated
     */
    SysExperienceList selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_experience_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysExperienceList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_experience_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(SysExperienceList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_experience_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysExperienceList record);
}