package com.hd.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.hd.domain.BasePage;
import com.hd.domain.SysExperienceList;

public interface SysExperienceListMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_experience_list
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_experience_list
	 * @mbggenerated
	 */
	int insert(SysExperienceList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_experience_list
	 * @mbggenerated
	 */
	int insertSelective(SysExperienceList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_experience_list
	 * @mbggenerated
	 */
	SysExperienceList selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_experience_list
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(SysExperienceList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_experience_list
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(SysExperienceList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_experience_list
	 * @mbggenerated
	 */
	int updateByPrimaryKey(SysExperienceList record);

    /**
     * 查询经验列表数据
     * @return
     */
    List<SysExperienceList> selectExperienceList();
    
    /**
     * 统计所有的装修效果记录
     * @return
     */
    int countExperience();
    
    List<SysExperienceList> selectExperienceLis(@Param("basePage")BasePage basePage,@Param("status")String status);
}