package com.hd.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.hd.domain.SysExperienceList;

public interface SysExperienceListMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_experience_list
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_experience_list
	 * @mbggenerated
	 */
	int insert(SysExperienceList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_experience_list
	 * @mbggenerated
	 */
	int insertSelective(SysExperienceList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_experience_list
	 * @mbggenerated
	 */
	SysExperienceList selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_experience_list
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(SysExperienceList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_experience_list
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(SysExperienceList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_experience_list
	 * @mbggenerated
	 */
	int updateByPrimaryKey(SysExperienceList record);

    /**
     * 查询有效的经验列表数据
     * @return
     */
    List<SysExperienceList> selectExperienceList();
}