package com.hd.mapper;

import java.util.List;

import com.hd.domain.SysMenu;
import com.hd.domain.SysMenuListInfo;

public interface SysMenuMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbggenerated
	 */
	int insert(SysMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbggenerated
	 */
	int insertSelective(SysMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbggenerated
	 */
	SysMenu selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(SysMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbggenerated
	 */
	int updateByPrimaryKey(SysMenu record);

	/**
     * 查询管理员菜单信息
     * @return
     */
    List<SysMenuListInfo> queryMenuList();
}