package com.hd.mapper;

import com.hd.domain.SysPreferentialActivities;

public interface SysPreferentialActivitiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_preferential_activities
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_preferential_activities
     *
     * @mbg.generated
     */
    int insert(SysPreferentialActivities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_preferential_activities
     *
     * @mbg.generated
     */
    int insertSelective(SysPreferentialActivities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_preferential_activities
     *
     * @mbg.generated
     */
    SysPreferentialActivities selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_preferential_activities
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysPreferentialActivities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_preferential_activities
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(SysPreferentialActivities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_preferential_activities
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysPreferentialActivities record);
}