package com.hd.mapper;

import java.util.List;

import com.hd.domain.DesignerCheckInfo;
import com.hd.domain.User;

public interface UserMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated
	 */
	User selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated
	 */
	int updateByPrimaryKey(User record);

	/**
     * 查询用户信息
     * @param user
     * @return
     */
    List<User> selectUserBySelective(User user);
    
    /**
     * 根据手机号查询用户是否存在
     * @param telphone 手机号码
     * @return
     */
    int userExists(String telphone);
    
    /**
     * 查询设计师申请审核信息
     * @return
     */
    List<DesignerCheckInfo> queryAllDesignerCheckInfo(DesignerCheckInfo designerCheckInfo);

	/**
	 * 统计申请审核的设计师
	 * @param designerCheckInfo
	 * @return
	 */
	Integer queryCountAllDesignerCheckInfo(DesignerCheckInfo designerCheckInfo);
    
    /**
     * 通过用户id查询设计师申请审核信息
     * @param userId 用户id
     * @return
     */
    DesignerCheckInfo queryDesignerCheckInfoById(String userId);
}